MapEd: Shortcut for units stack rows inc/dec by 10/100 rows
Kromster80/kam_remake pull request #116
Opened 2016-11-07 18:58 UTC by reyandme

Also MapEd small bugfix

2016-11-07 19:11 UTC, Kromster80 requested changes

2016-11-07 19:11 UTC, Kromster80 commented on src/gui/pages_maped/KM_GUIMapEdUnit.pas
> +    fGroup.UnitsPerRow := EnsureRange(fGroup.UnitsPerRow + GetMultiplicator(Shift), 1, 200);
`EnsureRange` looks superfluous here. `UnitsPerRow` already ensures the value is within 1..Count in its setter. Why do we need it here?

2016-11-07 19:11 UTC, Kromster80 commented on src/gui/pages_maped/KM_GUIMapEdUnit.pas
> +  if (fGroup.MapEdCount < fGroup.UnitsPerRow) then
Why do we need this check here?

2016-11-07 19:23 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdUnit.pas
> +  if (fGroup.MapEdCount < fGroup.UnitsPerRow) then
check out bug video on trello

2016-11-07 19:32 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdUnit.pas
> +    fGroup.UnitsPerRow := EnsureRange(fGroup.UnitsPerRow + GetMultiplicator(Shift), 1, 200);
fGroup.UnitsPerRow is Word type. At least we must ensure it more then 0.

2016-11-08 16:08 UTC, Kromster80 approved these changes

2016-11-08 16:08 UTC, merged