Map name label
Kromster80/kam_remake pull request #125
Opened 2016-11-12 19:01 UTC by andreus791

![image](https://cloud.githubusercontent.com/assets/13397574/20240197/8bbbcf70-a923-11e6-922b-3fd0242b79f3.png)

2016-11-13 01:01 UTC, lewinjh commented
It makes the interface look too crowded in my opinion.

2016-11-13 07:00 UTC, Kromster80 commented
As suggested on Trello: song name could go down between buttons (as it was in KaM iirc). 
Also take into account that whole menu must reasonably fit into smallest game window (1024*720 iirc).

2016-11-27 13:25 UTC, andreus791 commented
![image](https://cloud.githubusercontent.com/assets/13397574/20648663/24d6cc6e-b4be-11e6-8a08-c7d9cd3ce3ec.png)

2016-11-27 16:46 UTC, andreus791 commented
![default](https://cloud.githubusercontent.com/assets/13397574/20649871/e96d4fd8-b4d9-11e6-9869-cb26568abcaf.png)
![default](https://cloud.githubusercontent.com/assets/13397574/20649872/e96dfc1c-b4d9-11e6-9d98-6c8792832c7e.png)

Limited map name length (.InCastle 1.3 (Bonus)_Barb_Balanced_77FE8E32 --> .InCastle 1.3 (Bonus)_), dynamic interface to fit autowrapped track names.

2016-12-04 07:46 UTC, Kromster80 commented
Let's make the texts uniform:

Game time // yellow
hh:mm:ss // white

Map title // yellow
my_map_name // white

Music player // yellow
01_Busy // white

2016-12-10 11:47 UTC, andreus791 commented
Done, looks better now

![image](https://cloud.githubusercontent.com/assets/13397574/21073119/8b89a55c-bee7-11e6-8f7e-c3966c7a726f.png)

2016-12-13 09:43 UTC, Kromster80 requested changes

2016-12-13 09:43 UTC, Kromster80 commented on src/gui/KM_InterfaceDefaults.pas
> +  MAX_TRACKNAME_LENGTH = 18;
Let's move these 2 consts to a module where they are used. No need to make them "globally" visible.
After that PR can be merged )

2016-12-13 10:19 UTC, merged

2016-12-13 10:19 UTC, Kromster80 commented
Thanks!