Option to automatically pause the replay when peacetime ends
Kromster80/kam_remake pull request #136
Opened 2016-11-19 14:38 UTC by andreus791

2016-11-25 04:04 UTC, Kromster80 commented
Will this work well if a game is on a speedup?

See this line within gGame.Update: "for I := 1 to fGameSpeedMultiplier do"
that icreases current tick.
I'm also not happy with a separate checkibox in UI, maybe it could be
hidden (be just a flag in INI, disabled by default?)

On 19 November 2016 at 17:38, andreus791 <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Kromster80/kam_remake/pull/136
> Commit Summary
>
>    - Option to automatically pause the replay when peacetime ends
>    - Comments
>
> File Changes
>
>    - *M* KM_TextIDs.inc
>    <https://github.com/Kromster80/kam_remake/pull/136/files#diff-0> (1)
>    - *M* data/text/text.eng.libx
>    <https://github.com/Kromster80/kam_remake/pull/136/files#diff-1> (1)
>    - *M* src/gui/KM_InterfaceGamePlay.pas
>    <https://github.com/Kromster80/kam_remake/pull/136/files#diff-2> (14)
>
> Patch Links:
>
>    - https://github.com/Kromster80/kam_remake/pull/136.patch
>    - https://github.com/Kromster80/kam_remake/pull/136.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kromster80/kam_remake/pull/136>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEZ46mQNnX8axPSlwhaAoSAH0xaNrmV_ks5q_wnYgaJpZM4K3RLJ>
> .
>

2016-11-26 20:14 UTC, reyandme commented
write conslusion after discussion on skype:

2016-11-26 20:20 UTC, Kromster80 commented
And check/fix the pause on speedup

2016-12-04 07:54 UTC, Kromster80 requested changes

2016-12-04 07:54 UTC, Kromster80 commented on src/KM_Game.pas
> +                    PeaceTicksRemaining := Max(0, Int64((fGameOptions.Peacetime * 600)) - fGameTickCount);
Why do we need to cast explicitly to Int64?

2016-12-04 07:54 UTC, Kromster80 commented on src/KM_Game.pas
> +  PeaceTicksRemaining: Cardinal;
Better rename to `PeaceTimeLeft` - so we have keywords PeaceTime

2016-12-04 07:54 UTC, Kromster80 commented on src/gui/KM_InterfaceGamePlay.pas
> +
Unneeded line

2016-12-04 07:54 UTC, Kromster80 commented on src/gui/KM_InterfaceGamePlay.pas
> +procedure TKMGamePlayInterface.SetButtons(aPaused: Boolean);
Why do we need this function to become accessible from anywhere else?

2016-12-04 07:54 UTC, Kromster80 commented on src/gui/pages_game/KM_GUIGameMenuSettings.pas
> +    CheckBox_Settings_ReplayAutoPause.Hint := 'Automatically pause replay when peacetime ends'; //TODO translate
Please stick to Delphi format, including : ,  when adding todos like so "//todo:"

2016-12-13 09:55 UTC, merged

2017-01-23 05:58 UTC, reyandme commented
Now 'Replay qutopause option' is visible (but not enabled) during any game. I think we do need to show it (even in disabled state) unless its MP replay game mode.