Hotkeys bugfixes n improvements
Kromster80/kam_remake pull request #139
Opened 2016-11-24 18:05 UTC by reyandme

1. 	Do not allow to set Ctrl or Shift as key bindings
2. 	handle Tab for bindings
3 	Add ability to cancel changes of keys bindings

2016-11-25 20:08 UTC, reyandme commented
@lewinjh What do you think about these feactures ?
One thing I am not sure here - mb set no default keys for new extra 10 dynamic hotkeys (currently I set default keys as Numpad 1-9,0 same as for current 10 synamic hotkeys, but on Numpad.

2016-11-25 20:15 UTC, Kromster80 requested changes

2016-11-25 20:15 UTC, Kromster80 commented on src/gui/pages_menu/KM_GUIMenuOptions.pas
> +    destructor Destroy;
destructors must have "override;" keyword after them

2016-11-25 20:15 UTC, Kromster80 commented on src/hands/KM_Hand.pas
> +    SelectionHotkeys: array[0..19] of Integer;
Where does this magic number comes from? Const would be better

2016-11-25 20:15 UTC, Kromster80 commented on src/gui/KM_InterfaceGamePlay.pas
> +  if not InRange(aId, 0, length(fSelection) - 1) then Exit;
"length(fSelection) - 1" usually can be replaced with "High(fSelection)"

2016-11-25 20:27 UTC, reyandme commented on src/hands/KM_Hand.pas
> +    SelectionHotkeys: array[0..19] of Integer;
definitely

2017-01-22 15:52 UTC, Kromster80 commented
This PR is out of date and contains a lot of different changes. Please see if you can actualize it and split into several manageable chunks.

2017-01-23 05:03 UTC, reyandme commented
I've actualized this PR.

2017-02-26 02:30 UTC, lewinjh requested changes
Lets get this monster PR merged! Changes look good overall. Fixes these few things and I'll merge it.

One thought I had (for the future, this PR is big enough!): It would be nice to keep the keybindings compatible between updates (especially with frequent beta testing). This means we can't reorder items in KM_KeyIDs.inc, otherwise the bindings will be assigned to the wrong action after an update. Maybe give each area an offset (e.g. +1000 for faCommon, +2000 for faGame, etc.) so you can add more keys to the end of each section without rearranging. But obviously the fFuncs array shouldn't have 1000s of elements just because of these offsets, so you'd need to find a way to keep it compact (maybe by separating key IDs from fFunc indexes).

2017-02-26 02:30 UTC, lewinjh commented on src/gui/KM_InterfaceGamePlay.pas
> +      Exit;
Can be simplified by moving Exit above

2017-02-26 02:30 UTC, lewinjh commented on src/KM_Game.pas
> +    IsDefaultGameSpeedInReplayMP: Boolean;  // While watching MP replay we can set to default game speed as it was in MP game
I don't think this is necessary. If you've sped up the replay why should it suddenly return to the default speed at peacetime? The viewer can do that themselves.

2017-02-26 04:04 UTC, reyandme commented
@lewinjh Ok, I removed SC_REAL_GAME_SPEED hotkey as well as IsDefaultGameSpeedInReplayMP.

fFunc refactoring is better to do in separate PR, this one is tooooo big^)

2017-02-26 04:11 UTC, lewinjh approved these changes

2017-02-26 04:11 UTC, merged