Change default player colors.
Kromster80/kam_remake pull request #142
Opened 2016-11-26 20:06 UTC by reyandme

no need to stay with original KaM colors

2016-11-26 21:16 UTC, reyandme commented
May be complitely switch to our colors in MP_TEAM_COLORS ?
Because our, let say, red in MP_TEAM_COLORS, differs from KaM original hence DefaultTeamColors.
So we can put here our Red, Cyan, Green, Magenta, Yellow, Grey, Black, Orange, Blue, Light green, White and one other color (purple, for example)

2016-11-29 11:57 UTC, lewinjh commented
I agree it makes no sense keeping these default colours in the editor.

The reason for using the original colours was because some KaM campaign missions (TSK / TPR) don't specify the colours, but rely on the defaults. So with this change the black AI in TSK mission 20 might now be orange for example.

The best solution is probably checking that all of the TSK/TPR .dat files in KaM Remake do not rely on these defaults (and if they do set the colours and commit the fixed .dat files). Alternatively the .dat parser could use different default colours to the map editor.

2016-11-29 12:08 UTC, Kromster80 commented
I'd suggest to include the "color checking" code into the Batcher util (one
that we use to resave and other mass operations on all of the maps)

On 29 November 2016 at 14:57, Lewin <notifications@github.com> wrote:

> I agree it makes no sense keeping these default colours in the editor.
>
> The reason for using the original colours was because some KaM campaign
> missions (TSK / TPR) don't specify the colours, but rely on the defaults.
> So with this change the black AI in TSK mission 20 might now be orange for
> example.
>
> The best solution is probably checking that all of the TSK/TPR .dat files
> in KaM Remake do not rely on these defaults (and if they do set the colours
> and commit the fixed .dat files). Alternatively the .dat parser could use
> different default colours to the map editor.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kromster80/kam_remake/pull/142#issuecomment-263551866>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEZ46uQHbDfjTb-3aMT272UDP_t_wcH5ks5rDBMngaJpZM4K8-sL>
> .
>

2016-11-29 13:23 UTC, lewinjh commented
I forgot about batcher! That's the right place for it.

2016-12-04 07:43 UTC, Kromster80 commented
@reyandme please see the Batcher code and add a button there to mass-check all the maps (campaign, sp, mp, tutorials). All colors must be set explicitly. If they are not set - apply default TSK colors and resave.

2016-12-04 08:40 UTC, reyandme commented
Ok

2017-01-01 20:19 UTC, Kromster80 commented
@reyandme Did you have a chance to update the Batcher and all stock maps to have colors listed explicitly?

2017-01-02 00:42 UTC, reyandme commented
@Kromster80 I never checked Batcher code and what is going on here so its a low priority thing for me now.

2017-01-22 15:45 UTC, Kromster80 commented
Please check the Batcher and see if you can make a function in there to check/update all the KMR maps. Then this PR will be good to accept.

2017-02-06 01:57 UTC, reyandme commented
I took a look at the KMR color system finally. 
We have 3 commands to set player color in *.dat file: 
!SET_MAP_COLOR
!SET_RGB_COLOR
!SET_NEW_REMAP

The last one (!SET_NEW_REMAP) is disused. Btw it still exists in 1 MP map, about 10 SP Maps, and 3 Campaigns: TPS,TSK and Neryn.
Suggestion 1: delete all these !SET_NEW_REMAP from maps (manually by Notepad++,f.e., or with Batcher)

!SET_MAP_COLOR sets player color by 0-255 index from palette. There are several palettes, by could only find usage of only DefaultPalette, which is actually comes from file '/data/gfx/pal_0.bbm'.
I do not is there any real use of other *.bbm files, same for *.lbm files (not sure what is the difference, btw)
Suggestion 2: do not load unused palettes. Am I missing something ?
Question 3: it's not hard to get palette's contents, but do we have any kind of editor for them ? 

!SET_RGB_COLOR command sets player color to specified RGB value (which is written in decimal form, not hex form). If there are both commands (SET_MAP_COLOR and SET_RGB_COLOR), then the last command overrides previous one. MapEditor add both of them, when you save the game, so SET_MAP_COLOR is always unused. I do not know, why we need to add both, not just use SET_RGB_COLOR? Compatibility with original KaM ? We should parse them properly, ok, but there is no need to save them for new map.

Suggestion 4: Do not add SET_MAP_COLOR when save game in MapEditor.

And finally about using Default colors. 

As I understand, there is always either SET_MAP_COLOR or SET_RGB_COLOR or both. If there is SET_RGB_COLOR - then everything is fine, we get the color by its rgb code.
If there is only SET_MAP_COLOR, then it will be taken from palette, which is always the same, then the color will be fine as well.

@Kromster80 or @lewinjh please explain, what exaclty should this new func do in batcher for all SP/MP/Campaign maps?

Should we get rid of DefaultPalette at all ?

What I was talking about in the first comment is to get rid of KM_Defaults.DefaultTeamColors which are used as default colors in MapEd, and they have 2 black colors.

2017-02-07 00:53 UTC, lewinjh commented
Suggestion 1: This was used for minimap colour in KaM. Removing it is fine by me, although since it's ignored it's not really necessary to delete it.

Suggestion 2: The palette used to be needed for loading .rx files, that might not be needed in the main KaM Remake application now. Before you remove anything check that our tools/utils aren't using them either, for example RXXPacker needs to load other palettes IIRC (and I think it shares the same code).

Question 3: Palettes are not supposed to be changed. They're an old way of compressing sprites to only use 1 byte per pixel (both on disk and on GPU) by only having 256 colours available, chosen from a palette to suit the game's needs. We now convert everything to RGB during loading or in RXX packer. We only use palettes for !SET_MAP_COLOR to be able to load KaM mission files correctly. It uses the same palette as the .rx sprites were compressed with.

Suggestion 4: Agreed, this is a leftover from before we implemented !SET_RGB_COLOR. It can be removed now.

@reyandme The problem is if the .dat file does not use !SET_MAP_COLOR or !SET_RGB_COLOR for a player. In KaM it uses a colour from the default list of colours, so to maintain compatibility this is also what we do. If you change the default list of colours, this behaviour will be broken and so original KaM campaigns could load with the wrong player colours in cases where they did not specify but relied on the default colours. So if you want to change these default colours you need to make the batcher check all existing missions for teams that do not have a colour specified and add it. Or just change the default list that the map editor uses when you create a blank map, so that old KaM missions still load correctly.

2017-02-07 01:02 UTC, reyandme commented
Suggestion 1: not a big deal, but we parse this unused line :)
Suggestion 2: I believe they could be used by RXXPacker, so I do not want to remove their usage, but as you said, they are not needed for main game (not need waste time for loading unused resources, even if they not so much "time expensive")
Question 3: I do not want to edit them, but it would be nice to at least easily read them. Anyway its not a problem at all, just asking
Suggestion 4: Ok

Ok, I got it, I think it should be not difficult to add this func to batcher

2017-02-16 17:33 UTC, reyandme commented
New 4 buttons added to Batcher:

2017-02-19 08:12 UTC, lewinjh commented
@reyandme Yes unxoring the maps is fine by me. Maybe first unxor them, then apply these changes so that the changes are visible in github?

Does the map editor write unxored files now? If not it should.

2017-02-19 08:19 UTC, lewinjh requested changes

2017-02-19 08:19 UTC, lewinjh commented on Utils/Batcher/Unit1.dfm
> +      ' by either SET_MAP_COLOR or SET_RGB_COLOR command'
Hint is copied from above

2017-02-19 08:19 UTC, lewinjh commented on Utils/Batcher/Unit1.pas
> +    $FF000000  //Black
Looks like you copied your changed version by mistake. The original KaM default colours had black repeated.

2017-02-19 13:25 UTC, lewinjh approved these changes

2017-02-19 13:28 UTC, lewinjh commented
Thanks. Code changes all look good. Do you want to sort out the XORing and commit the .dat changes in this PR too?

2017-02-19 15:27 UTC, reyandme commented
> Does the map editor write unxored files now? If not it should.

I fixed this.

Last commit - I unXORed all maps (289 in total). In next PR we can apply *.dat files changes by new buttons I added here.

2017-02-19 21:55 UTC, reyandme commented
I decided to revert all maps unxor here, to be able to see other changes. For unxored maps there is another PR #

2017-02-20 11:18 UTC, merged