House not occupied message should mention which house it is ("This farm is not occupied")
Kromster80/kam_remake pull request #169
Opened 2016-12-17 14:57 UTC by reyandme

We need to add more TX_ labels for every house, because of plurals and fem/masc forms.

Task is from our buglist

2016-12-17 16:46 UTC, Kromster80 requested changes
That is a good idea to solve it like so. Please see about small improvement requests.

2016-12-17 16:46 UTC, Kromster80 commented on src/houses/KM_Houses.pas
> +var HouseNotOccupMsgId: Integer;
It's better to rename "NotOccup" to "Unoccupied", so that the term used is consistent.

2016-12-17 16:46 UTC, Kromster80 commented on src/houses/KM_Houses.pas
> +      if HouseNotOccupMsgId <> -1 then // HouseNotOccupMsgId should never be -1
If it is -1, then maybe we need to log this?

2016-12-17 16:46 UTC, Kromster80 commented on src/res/KM_Resource.pas
> +    function GetHouseNotOccupiedMsgId(aHouseType: THouseType): Integer;
It's better to rename "NotOccup" to "Unoccupied", so that the term used is consistent.

2016-12-17 16:46 UTC, Kromster80 commented on src/res/KM_Resource.pas
> +  case aHouseType of
This "case" is a bit superfluous, maybe we can do the usual house order trick?
`TX_MSG_HOUSE_UNOCCUPIED_ + Ord(HouseType)`

2016-12-18 07:46 UTC, reyandme commented on src/houses/KM_Houses.pas
> +var HouseNotOccupMsgId: Integer;
ок

2016-12-18 07:47 UTC, reyandme commented on src/res/KM_Resource.pas
> +    function GetHouseNotOccupiedMsgId(aHouseType: THouseType): Integer;
ok

2016-12-18 07:47 UTC, reyandme commented on src/res/KM_Resource.pas
> +  case aHouseType of
yep

2016-12-18 07:47 UTC, reyandme commented on src/houses/KM_Houses.pas
> +      if HouseNotOccupMsgId <> -1 then // HouseNotOccupMsgId should never be -1
okay

2016-12-24 13:14 UTC, merged