Fix delphi compilation hints
Kromster80/kam_remake pull request #212
Opened 2017-01-25 14:09 UTC by reyandme

2017-01-25 15:48 UTC, Kromster80 requested changes
Can you use this pattern?

2017-01-25 15:48 UTC, Kromster80 commented on src/gui/pages_menu/KM_GUIMenuMapEditor.pas
> +  Result := nil;
I came to a better pattern:

case of
  1:
  2:
else
  raise Exception.Create();
end;

It keeps compiler happy, takes less LOC and catches errors well.

2017-01-25 17:23 UTC, reyandme commented
I find this neater solution. I refactor all places where Assert(False) occurs.
And at least 4 times I find places where there was extra unused code. Compiler get more info about code when we use Exception.Create and can get some hints because of that.

There is still one last hint: unused private method:
`procedure TKMNetServer.SendMessageToRoom(aKind: TKMessageKind; aRoom: Integer; aParam: Integer);`
Can we delete it ?

2017-01-27 14:17 UTC, lewinjh commented
Yes it should be safe to delete SendMessageToRoom, I think it's a leftover from when we first implemented multiplayer. You only ever communicate to your own room, which is enforced by the server.

2017-01-27 14:21 UTC, reyandme commented
ok, I've deleted it

2017-01-28 03:36 UTC, merged