Update saved selection in list on save action
Kromster80/kam_remake pull request #216
Opened 2017-01-26 22:53 UTC by reyandme

In Map editor, on save map:
1. update saved position in map list on MapEd menu.
2. update radio btn MapType (SP/MP) on MapEd menu accordingly

In game, on save game:
1. update saved position in save list on Load game menu for SP games
2. update saved position in replay list on Replays menu
3. update radio btn ReplayType (SP/MP) on Replays menu accordingly

Then when player edit map, after save it will be his default choice
when player save game he will able to see his last game replay or load his last saved save easier.

Not sure if we need this for autosaves/
Also may be some players just never watch SP replays (which is reasonable, there no many things to watch), but sometimes play SP games, then they will be not happy with changed position of Replay type radio.
Then I can suggest to add ini setting for this rare occasion, to let ppl disable this 'autosave positions in lists' feature.

2017-01-28 03:26 UTC, lewinjh commented
Constants for map folders is good, thanks.

Auto selecting the last saved map/save for MapEd and singleplayer saves makes sense. I guess SP replays are ok too.

Autosave definitely should not change list positions, please confirm this isn't the case before I merge it.

Please lets not add INI settings for every possible tiny tweak like that. Otherwise we'll end up with 10 pages of settings that 99% of players don't use and don't understand what they do. Keep it simple.

2017-01-28 10:27 UTC, reyandme commented
> Autosave definitely should not change list positions, please confirm this isn't the case before I merge it.

It's not change the list positions now. Only manual save affect them.

Still not sure about replays. Most important save position here is radio btn for Replay type - many ofthe players usually watch only one type of replay (mostly MP replay, I believe), then autochanging radio btn to SP replay type on SP game save could confuse them. May we do not need update Replay positions on save.

2017-01-30 13:13 UTC, lewinjh commented
1. The lobby should have nothing selected when you enter it as host, for example you might want to discuss with other players in chat before selecting anything.
2. Does not seem necessary.
3. Remembering last selected campaign sounds ok to me. Probably no need to unselect it when finished, you might want to play a specific mission again.

2017-01-30 14:00 UTC, reyandme commented
Ok. I will add same feature for Campaigns later

2017-02-01 16:38 UTC, reyandme commented
> I guess SP replays are ok too.

> Still not sure about replays. Most important saved position here is radio btn for Replay type - many of the players usually watch only one type of replay (mostly MP replay, I believe), then autochanging radio btn to SP replay type on SP game save could confuse them.
So may we do not need update Replay positions on save.

@lewinjh What do you think about it ?

2017-02-12 21:26 UTC, reyandme commented
I removed update replay lists saved position on game save. Its not needed.

I added many string function here for KM_Utils.pas, because I used some of them in this PR. THese function needed for compilation on XE2. Also I will use them when implementing #247.

Unfortunally KM_Utils is also in linux lf endline format, so to see differences please merge #252 PR first.

2017-02-19 07:30 UTC, lewinjh requested changes
Please address the comments. Otherwise looks good though.

2017-02-19 07:30 UTC, lewinjh commented on src/KM_Game.pas
> +  MapInfo := TKMapInfo.Create(aPathName, True); //Force recreate map CRC
Don't we need to free MapInfo when we are finished with it?

2017-02-19 07:30 UTC, lewinjh commented on src/KM_Game.pas
> +  SaveInfo := TKMSaveInfo.Create(ExtractFilePath(fullPath), aSaveName);
Don't we need to free SaveInfo when we are finished with it?

2017-02-19 07:30 UTC, lewinjh commented on src/KM_Maps.pas
> +  raise Exception.Create('Unexpected map folder: ' + aFolderName);
Using Save from the F11 main menu might trigger this exception? It's not really unexpected to save outside of Maps and MapsMP.

2017-02-19 10:40 UTC, reyandme commented
Added fixes after review and conversation on skype

2017-02-19 11:53 UTC, lewinjh approved these changes

2017-02-19 11:53 UTC, merged