Added ability to change log specification by F11 debug window
Kromster80/kam_remake pull request #229
Opened 2017-02-01 23:51 UTC by reyandme

Also added ability to post logs into MP chat.

[!logs](https://puu.sh/tKh7j/2dcf832064.png)

2017-02-02 17:48 UTC, Kromster80 commented
Looks good to me. @lewinjh what do you say?

2017-02-07 01:05 UTC, lewinjh requested changes
Also looks good to me, just one minor issue I spotted

2017-02-07 01:05 UTC, lewinjh commented on src/KM_Utils.pas
> +      if not (aString[I-1] = ' ') then
On the first iteration this could check aString[0] which is out of bounds and will crash. You should start the iteration from 2 instead.

2017-02-07 01:08 UTC, reyandme commented on src/KM_Utils.pas
> +      if not (aString[I-1] = ' ') then
sure

2017-02-07 05:55 UTC, lewinjh approved these changes

2017-02-07 05:56 UTC, merged