MapEditor new feature: allow to grab an object with a MouseDown and drag it around until MouseUp
Kromster80/kam_remake pull request #235
Opened 2017-02-08 02:16 UTC by reyandme

Can drag units/group and houses.

Houses is a bit specail case, so I recorded a video for this:
http://youtu.be/8TwT-2mPa5s?hd=1

2017-02-11 12:06 UTC, lewinjh reviewed
The feature is great, I feel like the implementation might be over complicated though. Maybe it would be simpler to always drag houses using the wireframe so you can avoid the erase road issue altogether and not have two different dragging modes for houses?

Also have you checked what happens if you move the mouse outside the game window or alt-tab while dragging? That can sometimes lead to strange behaviour with mouse events (e.g. drag is never released).

2017-02-12 06:41 UTC, reyandme commented on src/gui/KM_InterfaceMapEditor.pas
> +    fStopMinimapUpdate: Boolean;  //Stop minimap from autoupdating, used in Drag House mechanism
may be not so much

2017-02-12 06:42 UTC, reyandme commented on src/hands/KM_Hand.pas
> +    function CanAddHousePlan(aLoc: TKMPoint; aHouseType: THouseType; aConsiderEntranceOffset: Boolean = True): Boolean;
ok, I'll check it

2017-02-12 07:13 UTC, reyandme commented on src/render/KM_RenderPool.pas
> +    cmHouses:     RenderWireHousePlan(KMVectorSum(P, gGameCursor.CellAdjustment), THouseType(gGameCursor.Tag1)); // Cyan quads and red Xs
I'll answer to this in comment down there

2017-02-12 07:20 UTC, reyandme commented
> Also have you checked what happens if you move the mouse outside the game window or alt-tab while dragging? That can sometimes lead to strange behaviour with mouse events (e.g. drag is never released).

I checked this situations:
- moving outside window does not make any problems, house is moved to the edge of the window, actually moved or not depends of map relief and objects
- when start drag object (or map, in DragScrolling feature) then alt+tab then release mouse btn, then alt+tab back to game window, then yes game thinks we are still in drag mode (object or scrolling), so f.e. any mouse move even without Holding mouse is fine. But then any Mouse Up event cancel it, as usual (for scrolling - its Middle btn mouse up only, for objects - any mouse up).

I am not sure now if we can handle alt+tab situation 100% clear, but we can add some protection from it: 
- on mouse move/mouse up check if proper mouse button is down in Shift state, so after alt-tab, if you do not have mouse down, drag mode will be reset.
- on any event (mouse down; key down/up - to avoid using hotkeys) except mouse up/mouse move - if we have DragObject (Scrolling) mode On, then reset it. 

About CellAdjustment:
Currently its reset, when *any* MouseUp event happens and we still have "DragObject" mode On (even on menu panel). 

But if we somehow change cursor mode avoiding mouseup event (by "2" hotkey, to open Houses page), then start f.e. build house somehow (future shortcut/using alt+tab, then mouse down+move any house) then yes we can get bug for a while.
But after protection I described above I do not see how we will be able to get it. We need sort of "finally" block - this (or other) protection should guarantee that.

Another approach (may be also nice one) is making gGameCursor a global variable of some TKMGameCursor class, then in Mode setter we will manage all "extra" states (CellAdjusment etc) and reset them if needed.

2017-02-18 17:37 UTC, Kromster80 commented
"Another approach (may be also nice one) is making gGameCursor a global variable of some TKMGameCursor class, then in Mode setter we will manage all "extra" states (CellAdjusment etc) and reset them if needed."

This is the way to go IMO. Just make sure TKMGameCursor known nothing about the gTerrain and such

2017-02-23 06:24 UTC, reyandme commented
@lewinjh @Kromster80 
I've done refactoring due to your suggestions.
- fStopMinimapUpdate removed
- aConsiderEntranceOffset removed
- CellAdjustment is managed in TKMGameCursor class, which replaced gGameCursor record
- alt-tab situations handled (also for dragScrolling mode) with my suggestion:

> on mouse move check if proper mouse button is down in Shift state, so after alt-tab, if you do not have mouse down, drag mode will be reset.

2017-02-26 03:47 UTC, lewinjh requested changes
Recent changes look good, it's much simpler with just one house dragging mode

2017-02-26 03:47 UTC, lewinjh commented on src/gui/KM_InterfaceMapEditor.pas
> +    fDragHouseEntranceTileOverlay: TTileOverlay; //Store tile overlay under house entrance, to avoid "road eraser" behaviour while dragging house
fDragHouseEntranceTileOverlay can be removed now

2017-02-26 03:47 UTC, lewinjh commented on src/gui/KM_InterfaceMapEditor.pas
> +    H.SetPosition(KMVectorSum(gGameCursor.Cell, fDragHouseGrabPntAdjustment));
Do we need to check if we are allowed to place the house here?

2017-02-26 03:47 UTC, lewinjh commented on src/houses/KM_Houses.pas
> +//aConsiderEntranceOffset - do consider house entrance offset while checking CanAddHousePlan and while set house to new position
Old comment about aConsiderEntranceOffset. Also it says it returns true but it's a procedure?

2017-02-26 04:07 UTC, reyandme commented on src/gui/KM_InterfaceMapEditor.pas
> +    H.SetPosition(KMVectorSum(gGameCursor.Cell, fDragHouseGrabPntAdjustment));
Check is inside SetPosition method already:
`if gMySpectator.Hand.CanAddHousePlan(aPos, HouseType) then`

2017-02-26 04:16 UTC, lewinjh approved these changes

2017-02-26 04:17 UTC, merged