Make Scripting parser utility compile under XE2
Kromster80/kam_remake pull request #253
Opened 2017-02-12 22:45 UTC by reyandme

2017-02-15 15:16 UTC, Kromster80 requested changes
Please review the comments

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +  Result := StartsStr(aSubStr, aStr);
Why not just replace StrStartsWith with StartsStr everywhere in code?

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +  Result := Copy(aStr, aFrom + 1, aLength);
Why not just replace StrSubstring with Copy everywhere in code?

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +  Result := AnsiPos(aSubStr, aStr) - 1;
Why not just replace StrIndexOf with Pos everywhere in code?

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +  Result := Copy(aStr, aFrom + 1, Length(aStr));
Why not just replace StrSubstring with RightStr everywhere in code?

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +  Result := StrIndexOf(aStr, aSubStr) <> -1;
Why not just replace StrContains with Pos() <> 0 everywhere in code?

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +var StrArray: TStringDynArray;
It's bad practice to create object (TStringList) inside and return it as parent class (TStrings). Do we really need it this way? Better to pass TStringList from outside in a parameter.

2017-02-15 15:16 UTC, Kromster80 commented on src/KM_Utils.pas
> +function StrSplitToStrArray(aStr, aDelimiters: String): TStringArray;
This function seems to be unused.

2017-02-15 15:44 UTC, reyandme commented
I will add these comments as Todo to code for future fixing then.

2017-02-16 17:11 UTC, merged

2017-02-16 17:11 UTC, Kromster80 commented
Merged with heavy heart. Hopefully "todos" will be resolved soon.

2017-02-19 07:08 UTC, lewinjh commented
I agree with Krom, reinventing our own versions of standard functions is a very bad idea. The compiler implementations will be significantly more efficient (often hand optimised assembly), and it makes the code less portable. I'd appreciate it if you can fix these todos soon.