Bug fixes Campaign builder
Kromster80/kam_remake pull request #256
Opened 2017-02-14 11:20 UTC by Alexandr57

Fixed most bugs Campaign builder

2017-02-19 07:59 UTC, lewinjh requested changes

2017-02-19 07:59 UTC, lewinjh commented on Utils/Campaign builder/Unit1.pas
> +  {http://gifok.net/images/2017/02/14/2017-02-14_16-01-27.gif}
Please don't write descriptions of your changes and links to gifs in the code. Post them in the description of the pull request.

In this case I would say this change doesn't require a comment in the code (instead post the gif and reasoning for your changes in the pull request description).

2017-02-19 07:59 UTC, lewinjh commented on Utils/Campaign builder/Unit1.pas
> +  //http://gifok.net/images/2017/02/14/2017-02-14_16-01-27.gif
As I said above, this comment should be in the pull request description not the code.

Here you should write a comment like "//SpinEdit can call OnChange with a value outside of the valid range, so validate it first"

2017-02-19 07:59 UTC, lewinjh commented on Utils/Campaign builder/Unit1.pas
> +    seMapCount.Value := EnsureRange(seMapCount.Value, seMapCount.MinValue, MAX_CAMP_MAPS);
There is no need for the if statement, you can always run EnsureRange here (result will be the same).

2017-02-19 07:59 UTC, lewinjh commented on Utils/Campaign builder/Unit1.pas
> +    seNodeCount.Value := EnsureRange(seNodeCount.Value, seNodeCount.MinValue, MAX_CAMP_NODES);
Same as my two comments on your other SpinEdit change

2017-02-19 09:50 UTC, Alexandr57 commented
@lewinjh 
If you remove this code:
if (seMapCount.Value > MAX_CAMP_MAPS)or(seMapCount.Value < seMapCount.MinValue) then
That there is such a problem:
http://gifok.net/images/2017/02/14/2017-02-14_16-01-27.gif
This is due to the fact that:
seMapCount.Value: = EnsureRange (seMapCount.Value, seMapCount.MinValue, MAX_CAMP_MAPS);
Re raises the event
OnChange
What do you advise?

2017-02-19 11:51 UTC, Alexandr57 commented
> Comments Rus

```
Вот так вам не нравится:
procedure TSpinEdit.CheckValue;
begin
  if not inRange(Value, MinValue, MaxValue) then
  Value := EnsureRange(Value, MinValue, MaxValue);
end;

А вот так:

procedure TSpinEdit.CheckValue;
begin
  Value := EnsureRange(Value, MinValue, MaxValue);
end;

Вызывает баг делая невозможным ввод вручную
```

> Comments Eng

```
So you do not like:

procedure TSpinEdit.CheckValue;
begin
  if not inRange(Value, MinValue, MaxValue) then
  Value := EnsureRange(Value, MinValue, MaxValue);
end;

And like this:

procedure TSpinEdit.CheckValue;
begin
  Value := EnsureRange(Value, MinValue, MaxValue);
end;

It is a bug making it impossible to input manually
```

> Here is the result of such an option code:
```
procedure TForm1.seMapCountChange(Sender: TObject);
begin
  if fUpdating then Exit;

  seMapCount.CheckValue;

  C.MapCount := seMapCount.Value;

  if fSelectedMap > C.MapCount - 1 then
    fSelectedMap := -1;

  UpdateList;
  UpdateFlagCount;
  RefreshFlags;
end;
procedure TForm1.MapChange(Sender: TObject);
begin
  if fUpdating or (fSelectedMap = -1) then Exit;

  seNodeCount.CheckValue;

  C.Maps[fSelectedMap].NodeCount := seNodeCount.Value;

  if fSelectedNode > C.Maps[fSelectedMap].NodeCount - 1 then
    fSelectedNode := -1;

  UpdateList;
  UpdateNodeCount;
  RefreshFlags;
end;
...
procedure TSpinEdit.CheckValue;
begin
  Value := EnsureRange(Value, MinValue, MaxValue);
end;
```
Result:
![2017-02-19_16-13-39](https://cloud.githubusercontent.com/assets/17384156/23102038/6ecab186-f6c3-11e6-91c7-fed554a78ac2.gif)
PS: I'm in SE introduced the 1 digit. He substituted a second.

2017-02-19 11:55 UTC, lewinjh commented
Don't set the spin edit value from within the change handler. Instead make a local copy of the value which has been checked with EnsureRange and use that within the change handler. We shouldn't be setting the value back to the spin edit, just validating it before we use it.

2017-02-19 12:15 UTC, Alexandr57 commented
@lewinjh 
That maximum value is set at the beginning:
```
procedure TForm1.FormCreate(Sender: TObject);
begin
  DoubleBuffered := True; //Makes images drag around smoothly
  ScrollBox1.DoubleBuffered := True;

  Caption := 'Campaign Builder (' + GAME_REVISION + ')';

  C := TKMCampaign.Create;
  fSelectedMap := -1;

  //This line corrects a bug in UpdateList namely C.CampName line that returns at the start of the program #0#0#0
  edtShortNameChange(nil);

  seMapCount.MaxValue := MAX_CAMP_MAPS;
  seNodeCount.MaxValue := MAX_CAMP_NODES;

  fSprites := TKMSpritePackEdit.Create(rxCustom, nil);

  seMapCountChange(nil); //Initialise it to 1 map
end;
```
If nothing is done then that's what will
![2017-02-19_17-14-37](https://cloud.githubusercontent.com/assets/17384156/23102207/ef002bf8-f6c6-11e6-939c-93b2a392f8e3.gif)
Or do you propose to write a new event that will occur before the OnChange

2017-02-19 12:27 UTC, Alexandr57 commented
![image](https://cloud.githubusercontent.com/assets/17384156/23102304/a564b80e-f6c8-11e6-8fe5-b42442c6735c.png)

2017-02-19 12:40 UTC, lewinjh commented
I've committed my proposed solution, take a look

2017-02-19 12:46 UTC, Alexandr57 commented
@lewinjh 
Sorry. Only now realized!
It can be like this:
```
C.MapCount := seMapCount.GetValue;
C.Maps[fSelectedMap].NodeCount := seNodeCount.GetValue;
...
function TSpinEdit.GetValue: Integer;
begin
  Result := EnsureRange(Value, MinValue, MaxValue);
end;
```
It'll do?

2017-02-19 13:03 UTC, lewinjh commented
No I don't like that. We don't need to customise the spin edit class. Just do the EnsureRange when we take the value from the view (spin edit) to the model (campaign data). Look at what I committed in master.

2017-02-19 13:05 UTC, Alexandr57 commented
Ok

2017-02-20 11:09 UTC, lewinjh approved these changes

2017-02-20 11:09 UTC, merged