Lobby: for player drop box new possibility new set all slots as open/closed/ai
Kromster80/kam_remake pull request #289
Opened 2017-02-23 03:33 UTC by reyandme

Added new column for drop list (actually its drop column now). 
'All' column should be small, to avoid unwanted clicks. To separate columns they use different colors for text. Also added highlighting for both columns with different colors.

Here how it looks now:

![all](https://puu.sh/ufHA9/d760a4a552.gif)

2017-02-24 07:59 UTC, Kromster80 requested changes

2017-02-24 07:59 UTC, Kromster80 commented on src/KM_Defaults.pas
> +  icRoyalYellow = $FF4AC7FF;
Please provide comments as to what these CONSTANT colors mean and where they are used and what for.

2017-02-24 07:59 UTC, Kromster80 commented on src/KM_Controls.pas
> +        if not aDoNotHighlight
Can we avoid double negation here by changing the var name to aHighlight ?

2017-02-24 18:05 UTC, reyandme commented on src/KM_Controls.pas
> +        if not aDoNotHighlight
aHighlight is not correct here, because we may highlight, or may not, depends on other reasons.
Probably aAllowHighlight is Ok here

2017-02-24 18:29 UTC, reyandme commented on src/KM_Defaults.pas
> +  icRoyalYellow = $FF4AC7FF;
We decided to do some refactoring on skype, smth like
clRed = 
clPingHigh = clRed
clFpsLow = clRed

Here, similar:

2017-02-24 21:09 UTC, reyandme commented
We decided to do some refactoring on skype with @Kromster80 , smth like
clRed =
clPingHigh = clRed
clFpsLow = clRed

Here, I'll refactor, smth like:
icRoyalYellow = $FF4AC7FF
clChatSomething = icRoyalYellow;
clLobbyOpponentAll = icRoyalYellow;

2017-02-25 07:50 UTC, Kromster80 commented
Looks good to me. I especially like the new Colors list. It looks tempting to move it to gRes.Colors now :-)

@lewinjh Please take a look and merge.

2017-02-25 07:50 UTC, Kromster80 approved these changes

2017-02-25 23:48 UTC, merged