BugFix: scripting action OnHousePlanRemove was invoked with wrong coord
Kromster80/kam_remake pull request #298
Opened 2017-02-25 23:01 UTC by reyandme

Bug occurs, because when we invoke OnHousePlanRemove we use location, where user clicks (then GIP command is produced with click coordinates). Instead we must use HousePlan coordinates

2017-02-25 23:59 UTC, lewinjh requested changes
Good catch, I never considered that :)

2017-02-25 23:59 UTC, lewinjh commented on src/KM_BuildList.pas
> +  Result := GetEmptyPlan;
I would prefer the function to return a boolean for success and pass the plan via an out parameter rather than having GetEmptyPlan.

2017-02-26 00:00 UTC, reyandme commented on src/KM_BuildList.pas
> +  Result := GetEmptyPlan;
ok

2017-02-26 00:01 UTC, reyandme commented
Well, actually this bug comes from Toxic at [kam.net](http://www.knightsandmerchants.net/forum/viewtopic.php?f=23&t=3228#p48118)

2017-02-26 00:14 UTC, lewinjh approved these changes

2017-02-26 00:15 UTC, lewinjh commented
After reading the kam.net topic I'm wondering if we are consistent with house positions in script events/actions/states. Do we always use the entrance? (I believe all actions use the entrance, but some events/states might not) I think this event will give the offset position of the plan not the entrance...

@reyandme Could you check this please?

2017-02-26 00:16 UTC, merged

2017-02-26 00:19 UTC, reyandme commented
@lewinjh may be we can ask @andreus791, he knows (and uses) scripts better then me :)