Ability to validate not only the file and all files and files in a folder
Kromster80/kam_remake pull request #316
Opened 2017-02-27 15:58 UTC by Alexandr57

Ability to validate not only the file and all files and files in a folder

2017-02-27 15:59 UTC, Alexandr57 commented
![image](https://cloud.githubusercontent.com/assets/17384156/23368409/94682d52-fd2f-11e6-9d7a-b2f6bf7f135b.png)

2017-02-28 15:43 UTC, Kromster80 requested changes

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +  IsValidatePath : Boolean;
Does not need to be global vars

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +procedure TForm1.FindFiles(Path: String; out aList: TStringList);
Why do you add "out" modifier? It should not be here

Also please mind the code standard - arguments start with "a" = aPath

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +var SearchRec:TSearchRec;
Please mind the code formatting. This should be:

var
  SearchRec: TSearchRec;

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +        if SameText(RightStr(SearchRec.Name, Length(EXT_FILE_SCRIPT)+1), ('.'+EXT_FILE_SCRIPT)) then
Looks quite complicated.
Should be SameText(ExtractFileExt(SearchRec.Name), EXT_FILE_SCRIPT)

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +  Edit1.Text := OpenDialog1.FileName;
Mind code formatting please

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +var DirValidate : String;
Mind code formatting please

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +    Memo1.Text := 'Select Files!';
Why is the text different, there you reference selectED folders, and here select files?

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +  Edit1.Enabled := false;
Would be better to move these 5 lines into a separate procedure.

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +    if SameText(RightStr(Edit1.Text, 1), PathDelim) then Edit1.Text := LeftStr(Edit1.Text, (Length(Edit1.Text) -1));
Should be ExcludeTrailingPathDelimiter(Edit1.Text)

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +  end else
No need for 2 extra empty lines above

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +        Memo1.Lines.Append('Checked ' + IntToStr(sListFileInFolder.Count) + ' in ..\..\');
Why do you add "' in ..\..\'" here?

2017-02-28 15:43 UTC, Kromster80 commented on Utils/ScriptValidator/Unit1.pas
> +procedure TForm1.btnValidateAllClick(Sender: TObject);
Below function looks like to have a lot of duplicate code with above. Are you sure they can not be merged?

2017-02-28 15:43 UTC, Kromster80 commented on src/KM_Defaults.pas
> +  EXT_FILE_SCRIPT = 'script';
Extensions should include the dot - ".script"

2017-11-11 04:11 UTC, Alexandr57 commented
Этот PR возможно нуждается в исправлении. Сейчас протестировать нет возможности.

This PR may need correction. Now there is no way to test it.

2017-11-11 15:24 UTC, Alexandr57 commented
Короче я проверил. Все работает. PR можете принимать или закрывать.
Делать возможность проверки каталога включая подкаталогов в консольном режиме я не буду. Пускай @thibmo этим занимается.
Как по мне проще было бы прикрутить консольный режим в графическом виде чем в консольном используя ParamStr() при создании формы.

In short, I checked. Everything is working. PR can accept or close.
Make the ability to check the directory including subdirectories in the console mode I will not. Let @thibmo do it.
As for me it would be easier to tighten the console mode in a graphical form than in the console using ParamStr () when creating the form.

2017-11-27 10:07 UTC, thibmo commented
We can always change the implementation of the console/GUI mode switch. :)
Issue with GUI mode is that it calls the Windows API in a different way, meaning it will always spawn a GUI, now imagine a map scripter that works with Linux CLI and only uses the GUI for gaming..
Making a console in the GUI is a no-go in this case.
Hence the console-first approach. :)

As for the edits, sure can implement those if needed. :)

Quick explanation:
Console mode detection "magic" is done with this code:
```Pascal
function IsConsoleMode: Boolean;
var
  SI: TStartupInfo;
begin
  SI.cb := SizeOf(StartUpInfo);
  GetStartupInfo(SI);
  Result := (SI.dwFlags and STARTF_USESHOWWINDOW) = 0;
end;
```
So it SHOULD still start with GUI by default when you start the app whilst dragging a file to the app. (As in, open with a file)
'-g' / '-graphic' are only  to force GUI mode when started from CMD/PowerShell.

2018-06-18 16:59 UTC, closed without merging

2018-06-18 18:07 UTC, Kromster80 commented
Abandoned