Unit group: feed or split should not cancel group command
Kromster80/kam_remake pull request #332
Opened 2017-03-04 17:23 UTC by reyandme

If group has some order (walk/attack unit/house) then it is usually continue it after some group command was initiated (change rows count, turn left or right, link). But for some reason group get halt order on feed and split command. Its very unpleasant - player send his troops to some point, then he wanted to feed them or split - and group stop going to that point, making formation instead.

This PR fixes this issue.

2017-03-08 08:52 UTC, lewinjh requested changes
I guess we did it that way because that's what KaM did. I agree with you, it's better not to halt in these situations.

2017-03-08 08:52 UTC, lewinjh commented on src/units/KM_UnitGroups.pas
> +procedure TKMUnitGroup.OrderRepeat(aGroup: TKMUnitGroup);
Lets leave the old OrderRepeat as is and add a new procedure, CopyOrderFrom(aGroup). Less confusing that way and it's a short procedure so not much duplication.

2017-03-08 08:55 UTC, reyandme commented on src/units/KM_UnitGroups.pas
> +procedure TKMUnitGroup.OrderRepeat(aGroup: TKMUnitGroup);
ok, I agree

2017-03-14 00:27 UTC, lewinjh approved these changes

2017-03-14 00:27 UTC, merged