Added display color code BGR Remake
Kromster80/kam_remake pull request #337
Opened 2017-03-06 03:02 UTC by Alexandr57

Added display color code BGR Remake

2017-03-06 10:30 UTC, reyandme commented
I suggest to allow user to copy from TKMEdit.
To do that you will need to remove 'ReadOnly' attribute and add OnKeyDown handler for your new Edit field, where you you do not allow anything exept Ctrl+A and Ctrl+C (just ignore all other input).

Rus translation:
(Предлагаю добавить копирование из элемента TKMEdit.
это можно сделать убрав атрибут 'ReadOnly' и добавив обработчик события OnKeyDown для твоего нового элемента TKMEdit, где нужно разрешить только нажатие клавиш Ctrl+A и Ctrl+C, все остальное - игноририовать)

2017-03-06 17:20 UTC, Kromster80 requested changes

2017-03-06 17:20 UTC, Kromster80 commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
> +  Result := IntToHex(aColor and $00FFFFFF, 6);
Should be Result := IntToHex(aColor and $FFFFFF, 6);

2017-03-06 17:20 UTC, Kromster80 commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
> +    BGRCodeEdit: TKMEdit;
Please use standard naming convention for controls

2017-03-06 18:00 UTC, Alexandr57 commented
@reyandme 
The OnKeyDown can not make entry ban only OnKeyPress OnKeyPress but does not work with Ctrl + A and Ctrl + C

2017-03-06 18:25 UTC, reyandme commented
@Alexandr57 
its better if you answer in russian, cause I did not understand you.
Our components are 100% self made, so we manage all key down event manually in KM_Controls unit. 
I added Ctrl+A and Ctrl+C and other key handling recently . Check r6720 - there is no copy paste from TKMEdit.

2017-03-07 11:04 UTC, reyandme requested changes
I suggested to @Alexandr57 to add BlockInput field to TKMEdit, as it can be used somewhere else and its better, then add OnKeyDown and OnKeyPress to TKMMapEdPlayerColors, where we will need to handle VK_LEFT and use other keys details.

2017-03-07 11:04 UTC, reyandme commented on src/KM_Controls.pas
> +    BlockInput: Boolean;//Lock input
Please this change comment to
// Blocks all input into the field, but allow focus, selection and copy selected text

2017-03-07 11:04 UTC, reyandme commented on src/KM_Controls.pas
> +  if BLockInput and not ((Key in [VK_LEFT, VK_RIGHT, VK_HOME, VK_END]) or ((ssCtrl in Shift) and (Key in [Ord('A'), Ord('C')]))) then Exit;
Can you split this long condition into several lines ? It will be easier to read it.
Also pls fix this: 'BlockInput', instead of 'BLockInput'

2017-03-07 11:04 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
> +  Edit_BGRCode.BlockInput := true;
Use 'True' instead of 'true', as we do everywhere.

2017-03-07 11:07 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
Please add new line, as we use 2 empty lines as procedures separator

2017-03-07 11:07 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
Please add new line, as we use 2 empty lines as procedures separator

2017-03-07 11:21 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
> +function TKMMapEdPlayerColors.GetCodeBGRColor(aColor: Cardinal): String;
We usually set 2 empty lines between methods, not only 1.
Между функциями мы ставим 2 пустые строки, а не 1.

2017-03-07 11:21 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
> +end;
We usually set 2 empty lines between methods, not only 1.
Между функциями мы ставим 2 пустые строки, а не 1.

2017-03-07 11:23 UTC, reyandme commented on src/gui/pages_maped/KM_GUIMapEdPlayerColors.pas
> +  Edit_BGRCode.BlockInput := true;
Please use 'True' instead of 'true'
Используй 'True' вместо 'true'

2017-04-23 07:22 UTC, merged