Fixed return of color through PlaerkolorTekst function in dynamic scripts
Kromster80/kam_remake pull request #338
Opened 2017-03-06 03:13 UTC by Alexandr57

PlayerColorText function returns the wrong shade of color
More details on the screenshot:
![image](https://cloud.githubusercontent.com/assets/17384156/23595558/98534658-0244-11e7-8963-7d604c74bbe4.png)
1 Variant - Result := IntToHex(aColor and $00FFFFFF, 6);
2 Variant - Result := AnsiString(Format('%.6x', [FlagColorToTextColor(aColor) and $FFFFFF]));

2017-03-06 17:16 UTC, Kromster80 requested changes

2017-03-06 17:16 UTC, Kromster80 commented on src/scripting/KM_ScriptingStates.pas
> +      Result := IntToHex(gHands[aPlayer].FlagColor and $00FFFFFF, 6)
Should be:
Result := IntToHex(gHands[aPlayer].FlagColor and $FFFFFF, 6)

2017-03-06 17:16 UTC, Kromster80 commented on src/scripting/KM_ScriptingStates.pas
> +      //Result := AnsiString(Format('%.6x', [FlagColorToTextColor(gHands[aPlayer].FlagColor) and $FFFFFF]))
Remove this line please

2017-03-08 06:32 UTC, merged

2017-03-08 07:17 UTC, lewinjh commented
This was intentional. The player colours for the GUI are lighter and desaturated so they are more readable. These are the same colours we use in other parts of the interface, like the player list and statistics screen.

You'll notice "1 Variant" is harder to read on a variety of backgrounds (black text is impossible to read without this feature)

2017-03-08 07:23 UTC, lewinjh commented
Reverted and added a comment to avoid future confusion