Updating or adding a dynamic script analogue PlayerColorText
Kromster80/kam_remake pull request #345
Opened 2017-03-08 14:44 UTC by Alexandr57

At this stage, I just updated the function of the TextbookText so that it returns not only the clarified color but also the original + so that the function remains compatible with the old scripts.
If you do not like it, I can add a separate one.
If you say that it's not obvious then In the wiki you can update

Here's what it looks like:
![2017-03-08](https://cloud.githubusercontent.com/assets/17384156/23708404/9849d7ae-0437-11e7-92c2-9395255cfe31.png)
Using:
procedure OnMissionStart;
begin
	Actions.OverlayTextSet(0, '[$'+States.PlayerColorText(0)+']1 Variant|[$'+States.PlayerColorText(0, false)+']2 Variant');
end;

2017-03-09 15:16 UTC, Alexandr57 commented
@Kromster80  has already unsubscribed to me.
Requires the views of @lewinjh

2017-03-09 15:45 UTC, reyandme requested changes

2017-03-09 15:45 UTC, reyandme commented on src/scripting/KM_ScriptingStates.pas
> +  bLight: Boolean): AnsiString;
We use 'a' prefix for parameters, so pls change 'bLight' to 'aLight'.
Also why did you start new line here ?

2017-03-09 15:45 UTC, reyandme commented on src/scripting/KM_ScriptingStates.pas
> +
No need for empty line

2017-03-09 15:46 UTC, reyandme commented
I added comments regarding code style.
Anyway @lewinjh should approve this changes first.

2017-03-09 15:56 UTC, Alexandr57 commented
Not only @lewinjh  but @Kromster80
Kakto @Kromster80  is not enthusiastic but as already said it does not change the original function. So the old scripts, as seen on the screenshot, will work as well.
(Не только @lewinjh  но и @Kromster80 
Както @Kromster80  не в восторге но как уже сказано она не изменит оригинальную функцию. Так что старые скрипты как видно на скрине будут работать также.)

2017-03-14 00:19 UTC, lewinjh commented
Why do you need the original colour in the scripts? What can it be used for? As far as I'm aware the only use for colours in the script is to colour GUI text. If you use the original colours for text they are unreadable. This is the reason why we desaturate and lighten the colours for the GUI and script, since it makes unreadable colours like black readable, and highly saturated colours like red less hard on the eyes. The colours are still very close to the original and will not cause confusion.

For example compare black text with the original colour and the GUI/script version.

2017-03-14 09:18 UTC, Alexandr57 commented
In some cases, the original color is very useful. Okay close but completely forbid using the original colors you can not. Personally, I hoped that there would be such a function. Well then, I will continue to use the color picker utility

2017-03-14 09:23 UTC, closed without merging