Ability to change school training order
Kromster80/kam_remake pull request #98
Opened 2016-11-01 08:51 UTC by reyandme

When clicked on train btn: 
Shift+LMB - train immediately (cancel current training)
Ctrl+LMB - train next (put on 1st position in queue)
Same behaviour when clicking in the training queue bar

2016-11-01 09:13 UTC, reyandme commented
There is a record in Buglist.txt about this feature:
Right-click on a unit in Schools queue to move that unit to the front of the queue (currently RMB is "remove to here")

2016-11-01 10:57 UTC, Kromster80 requested changes
Please fix mentioned comments

2016-11-01 10:57 UTC, Kromster80 commented on src/houses/KM_HouseSchool.pas
> +  I: Byte;
It is better to stick to using Integers for loops, since High(something) could be -1 and being cast to uint it becomes maxUInt-1.

2016-11-01 10:57 UTC, Kromster80 commented on src/houses/KM_HouseSchool.pas
> +      Continue
These two lines are misleading and should be just be omited

2016-11-01 18:19 UTC, reyandme commented on src/houses/KM_HouseSchool.pas
> +      Continue
Yep. Forget them after some refactoring.

2016-11-01 18:24 UTC, reyandme commented
Fixed

2016-11-01 18:43 UTC, Kromster80 requested changes

2016-11-01 18:43 UTC, Kromster80 commented on src/gui/pages_game/KM_GUIGameHouse.pas
> +      ChOrderFrom := max(School.LastUnitPosInQueue, 1);
I suspect calculation of `ChOrderFrom` should be moved into GIP command processing, as `LastUnitPosInQueue` can change during lag between click and execution.

2016-11-01 18:43 UTC, Kromster80 commented on src/gui/pages_game/KM_GUIGameHouse.pas
> +    procedure House_SchoolUnitBarPressed(Sender: TObject; Shift: TShiftState);
Please rename to `House_SchoolUnitQueueClick`, because there's no Bar Pressed

2016-11-01 18:43 UTC, Kromster80 commented on src/gui/pages_game/KM_GUIGameHouse.pas
>    if Sender = Button_School_Train then //Add unit to training queue
This comment should be updated to reflect new code

2016-11-01 18:43 UTC, Kromster80 commented on src/gui/pages_game/KM_GUIGameHouse.pas
> +      gGame.GameInputProcess.CmdHouse(gic_HouseSchoolTrain, School, School_Order[fLastSchoolUnit], 1);
Code comments are very much needed in here, explaining what is happening

2016-11-01 18:43 UTC, Kromster80 commented on src/gui/pages_game/KM_GUIGameHouse.pas
> +{Process click on Units bar buttons of School}
Please change into:
// Process click on Units queue buttons of School

as mentioned above, there's no unit "bar"

2016-11-01 18:43 UTC, Kromster80 commented on src/houses/KM_HouseSchool.pas
> +    procedure CreateUnit; //This should Create new unit and start training cycle
Good to see some refactoring and comments here :-)

2016-11-01 19:54 UTC, reyandme commented
Added new command gic_HouseSchoolTrainChLastUOrder to change orde for last unit in queue.
Tried to squash 2 commits in 1, but because 1st was pushed already so it appears in here anyway. And also another empty commit for merge appears (last one).

2016-11-02 04:22 UTC, Kromster80 commented
Now commits are fine, because overall PR contains just one feature and it is clearly trace-able.

2016-11-02 04:23 UTC, merged